name: 'Regenerate Embeddings'
description: 'Regenerate OpenAI word embeddings on every push and store them in Supabase'
author: 'K02D'
inputs:
  github-personal-access-token:
    description: 'Github personal access token'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  supabase-anon-key:
    description: 'Supabase anon key'
    required: true
  supabase-url:
    description: 'Supabase url'
    required: true
  repository-owner-username:
    description: 'GitHub username of the repository owner'
    required: true
  repository-name:
    description: 'Name of the repository'
    required: true
  path-to-contents:
    description: 'Path to the directory containing notes content'
    required: true
  directory-structure:
    description: "Either 'nested' or flat'. 'nested': `path-to-contents` points to a list of directories. 'flat': `path-to-contents` points to a list of files"
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
